# Use an official Python runtime as a parent image
FROM python:2

# Set the working directory to /app
WORKDIR C:\Users\DA063101\Documents\Website-Automation-using-Selenium\WebAutomation

# Install any needed packages specified in requirements.txt
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Run app.py when the container launches
CMD ["python", "test_all.py"]
